name: tests

on:
    push:
        branches:
            - '**'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    tests:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4.1.7
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4.0.3
              with:
                  node-version-file: '.nvmrc'
            - name: run test
              shell: bash
              run: |
                  npm i npm
                  npm ci
                  npm test